    # Annotation info
IMG_DIR: D:/ADPT/data/mouse/labeled-data
JSON: D:/ADPT/data/mouse/mouse.json

    # Image info
IMG_SIZE_H_ori: 964
IMG_SIZE_W_ori: 1288
channels: 3

    # Training image size
global_scale: 0.5
IMG_SIZE_H: 480
IMG_SIZE_W: 640

    # Model info
initial_weight: None
shuffle_num: 117481
early_stop: True
BATCH_SIZE: 8
variation: 17 / 8
initial_learning_rate: 1e-3
alpha: 1e-5
EPOCHS: 300
WARMUP_EPOCHS: 10
TrainingFraction: 0.95
Tranfer_LR: 1e-3
NUM_KEYPOINT: 16
centre: 3
delta: 0.025
num_classes: 1
bodyparts: 
- nose
- left_ear
- right_ear
- neck
- left_front_limb
- right_front_limb
- left_hind_limb
- right_hind_limb
- left_front_claw
- right_front_claw
- left_hind_claw
- right_hind_claw
- back
- root_tail
- mid_tail
- tip_tail
skeleton:
- (0,1)
- (0,2)
- (1,2)
- (2,3)
- (1,3)
- (3,4)
- (3,5)
- (4,5)
- (4,6)
- (4,8)
- (5,7)
- (6,7)
- (5,9)
- (6,10)
- (7,11)
- (3,12)
- (4,12)
- (5,12)
- (6,12)
- (7,12)
- (13,12)
- (7,13)
- (6,13)
- (13,14)
- (14,15)

